### PR TITLE
fix mouse wheel event recognition

### PR DESCRIPTION
**Pull request by fazibear**

### CODE REVIEW

**Comment by meh** [comment]
Just to verify, does the `wheel` event actually exist anywhere or did I make it up?

**Comment by vais** [comment]
@meh `wheel` is standard, `mousewheel` is non-standard and deprecated (see https://developer.mozilla.org/en-US/docs/Web/Events/wheel). In other words, we need both :wink:

**Comment by fazibear** [comment]
True. `wheel` if for `onwheel`, `mousewheel` if for `onmousewheel` event.

**Comment by meh** [comment]
Merged, thanks :panda_face:

**Pull request closed without merging**
