### PR TITLE
[IE11] Fixed support check for Event.constructor

### PR DESCRIPTION
**Pull request by MichaelSp**
This check works on IE11

### CODE REVIEW

**Comment by elia** [comment]
@meh just as a remainder, this change is necessary since `rescue` now ignores JS errors (except maybe those inheriting from `Error`).

**Comment by MichaelSp** [comment]
anything I can do to get this released?

**Comment by MichaelSp** [comment]
ping @meh @elia

**Comment by MichaelSp** [comment]
necessary change not merged since 6 month? Not so necessary?

**Comment by elia** [comment]
@MichaelSp I was about to suggest to change the PR to `rescue JS::Exception` instead of using `try/catch`. But looking again `try/catch` won't break backwards compatibility.

Please ping me if you submit other PRs like this and I'll try my best to help and get things merged.

**Comment by MichaelSp** [comment]
Thanks elia! I currently have no other PR.

**Pull request merged**
