### PR TITLE
fix browser storage

### PR DESCRIPTION
**Pull request by fazibear**

### CODE REVIEW

**Comment by meh** [comment]
I'm pretty sure to recall that was on purpose, because the storage keys can only be strings.

**Comment by fazibear** [comment]
In this situation keys instead of `"smth"` become `"\"smth\""`.
Example:
```ruby
    storage[:test] = {}
    puts storage[:test] # => {}
    storage.reload
    puts storage[:test] # => nil
```

**Comment by meh** [comment]
Yes, it's intended, that way you can use anything as key, as is commong with `Hash`.

**Comment by meh** [comment]
It seems like something else is broken in the reloading.

**Comment by fazibear** [comment]
So maybe it should use `to_s` instead of `to_json` twice ?
```ruby
    @data.each {|key, value|
      io << key.to_s.to_json << ":" << value.to_json << ","
    }
```

**Comment by meh** [comment]
Maybe `.to_json.to_s.inspect`.

**Comment by fazibear** [comment]
Both `.to_json.to_s` and `.to_s.to_json` work. And you suggest first one is better :+1:

**Comment by meh** [comment]
Merged.

**Pull request closed without merging**
